import { StatusPill } from "@/components/StatusPill";
import { FantasyProsControl } from "@/components/FantasyProsControl";
import { TrashTalkControl } from "@/components/TrashTalkControl";
import { api } from "@/lib/api";
import type { ManagerPlayer } from "@/lib/types";

export const dynamic = "force-dynamic";

export default async function ManagerPage() {
  const [plan, fantasyProsQuota, projectionBacktest, championshipBacktest, acquisitionLifecycle, notifications, trashTalk] = await Promise.all([
    api.manager(),
    api.fantasyProsQuota(),
    api.projectionBacktest(),
    api.championshipBacktest(),
    api.acquisitionLifecycle(),
    api.notifications(),
    api.trashTalk(),
  ]);
  const decision = plan.decision;
  const lineupPreview = plan.lineup_execution_preview ?? [];
  const waiverPreview = plan.waiver_execution_preview ?? [];
  const lineupExecution = plan.lineup_execution;
  const acquisitionExecution = plan.acquisition_execution;
  const waiverHorizon = decision?.waiver_horizon;
  const pendingWaivers = plan.season_horizon?.pending_waiver_claims ?? [];
  const researchEvidence = decision?.research_evidence ?? [];
  const tradeTargets = decision?.trade_targets ?? [];
  const incomingTradeDecisions = decision?.incoming_trade_decisions ?? [];
  const tradePreview = plan.trade_execution_preview ?? [];
  const tradeExecution = plan.trade_execution;
  const irPlan = plan.ir_plan;
  const recentNotices = notifications.filter((item) => item.channel === "dashboard").slice(0, 5);
  const evidenceGate = plan.data_quality?.evidence_gate;
  const championship = plan.championship_outlook;
  const championshipLive = championship?.model_diagnostics?.live_current_week?.our_team;
  const championshipFeatures = Object.entries(championship?.decision_features ?? {});
  const championshipCalibration = Object.entries(championshipBacktest.component_calibration ?? {});
  const moveCounterfactuals = championship?.roster_move_counterfactuals?.candidates ?? [];
  const championshipFeatureLabels: Record<string, string> = {
    live_score_and_remaining_players: "Live score and remaining players",
    injury_availability_scenarios: "Injury and availability scenarios",
    cross_player_correlations: "Cross-player correlations",
    future_opponent_effects: "Future opponent effects",
    multi_week_projection_decay: "Multi-week projection decay",
  };
  const intelligence = plan.intelligence;
  const calibration = projectionBacktest.ensemble_calibration;
  const players = [
    ...(plan.our_team?.all_players ?? []),
    ...(plan.free_agent_candidates ?? []),
  ];
  const playerById = new Map(players.map((player) => [player.player_id, player]));
  const name = (playerId: string) => playerById.get(playerId)?.name ?? playerId;
  const detail = (player?: ManagerPlayer) =>
    player ? [player.position, player.team, player.injury_status].filter(Boolean).join(" · ") : "";
  const rosterEnsembles = (plan.our_team?.all_players ?? [])
    .map((player) => player.projection_ensemble)
    .filter((projection) => projection?.disagreement != null);
  const averageDisagreement = rosterEnsembles.length
    ? rosterEnsembles.reduce((total, projection) => total + Number(projection?.disagreement ?? 0), 0) / rosterEnsembles.length
    : null;

  return <>
    <header className="pageHeader"><div><p className="eyebrow">Championship command center</p><h1>Season manager</h1><p>Whole-roster lineup, waiver, and risk decisions grounded in the live league.</p></div><StatusPill status={plan.autopilot_state ?? plan.manager_state}/></header>
    <section className="metricGrid">
      <article className="metric"><small>Week</small><strong>{decision?.week ?? plan.week ?? "—"}</strong><span>2026 regular season</span></article>
      <article className="metric"><small>Decision confidence</small><strong>{decision ? `${Math.round(decision.confidence * 100)}%` : "—"}</strong><span>{decision?.decision_status ?? plan.manager_state}</span></article>
      <article className="metric"><small>Lineup</small><strong>{decision?.lineup_status ?? "Waiting"}</strong><span>{decision?.lineup_changes.length ?? 0} proposed changes</span></article>
      <article className="metric"><small>Waivers</small><strong>{decision?.waiver_status ?? "Waiting"}</strong><span>{decision?.waiver_claims.length ?? 0} ordered claims</span></article>
    </section>
    {evidenceGate ? <section className={`panel full ${evidenceGate.status === "blocked" ? "managerBlockers" : ""}`}><div className="panelHeader"><div><p className="eyebrow">Deterministic safety control</p><h2>Evidence gate</h2></div><StatusPill status={evidenceGate.status}/></div><p className="decisionCopy">Reasoning: {evidenceGate.allows_reasoning ? "allowed" : "blocked"} · Lineup execution: {evidenceGate.allows_lineup_execution ? "allowed" : "blocked"}</p>{[...evidenceGate.blockers, ...evidenceGate.warnings].length ? <ul className="compactList">{[...evidenceGate.blockers, ...evidenceGate.warnings].map((item) => <li key={item}>{item}</li>)}</ul> : null}</section> : null}
    <FantasyProsControl initial={fantasyProsQuota} averageDisagreement={averageDisagreement} rosterProjectionCount={(plan.our_team?.all_players ?? []).filter((player) => player.projection_ensemble?.sources?.some((source) => source.source === "fantasypros")).length}/>
    <TrashTalkControl initial={trashTalk}/>
    {intelligence ? <section className="panel full"><div className="panelHeader"><div><p className="eyebrow">Promotion control</p><h2>Intelligence authority</h2></div><StatusPill status={intelligence.mode}/></div><div className="metricGrid"><article className="metric"><small>Usage snapshots</small><strong>{intelligence.snapshots_persisted.usage}</strong><span>{intelligence.usage_features_enabled ? "persisted this week" : "disabled"}</span></article><article className="metric"><small>Projection snapshots</small><strong>{intelligence.snapshots_persisted.projections}</strong><span>{intelligence.projection_ensemble_enabled ? "persisted this week" : "disabled"}</span></article><article className="metric"><small>Simulation runs</small><strong>{intelligence.snapshots_persisted.simulations}</strong><span>{intelligence.championship_simulation_enabled ? "fail-closed" : "disabled"}</span></article><article className="metric"><small>Decision authority</small><strong>{intelligence.mode === "authoritative" ? "Live" : "Locked"}</strong><span>{intelligence.mode === "authoritative" ? "qualified inputs enabled" : "shadow evidence cannot drive clicks"}</span></article></div>{intelligence.promotion ? <ul className="compactList"><li>Projection ensemble: {intelligence.promotion.projection.authoritative ? "authoritative" : intelligence.promotion.projection.eligible ? "qualified, awaiting master switch" : "shadow until empirical checks pass"}</li><li>Championship simulation: {intelligence.promotion.championship.authoritative ? "authoritative" : intelligence.promotion.championship.eligible ? "qualified, awaiting master switch" : "shadow until projection and structural checks pass"}</li></ul> : null}</section> : null}
    {calibration ? <section className={`panel full ${calibration.qualification_status === "qualified" ? "" : "managerBlockers"}`}><div className="panelHeader"><div><p className="eyebrow">Walk-forward validation</p><h2>Projection promotion gate</h2></div><StatusPill status={calibration.qualification_status}/></div><div className="metricGrid"><article className="metric"><small>Completed weeks</small><strong>{calibration.completed_weeks.length}</strong><span>2 required</span></article><article className="metric"><small>Pregame samples</small><strong>{calibration.candidate.samples ?? 0}</strong><span>40 required</span></article><article className="metric"><small>Ensemble MAE</small><strong>{calibration.candidate.mae == null ? "—" : calibration.candidate.mae.toFixed(2)}</strong><span>vs {calibration.strongest_paired_source ?? "awaiting baseline"}</span></article><article className="metric"><small>P20–P80 coverage</small><strong>{calibration.candidate.p20_p80_coverage == null ? "—" : `${Math.round(calibration.candidate.p20_p80_coverage * 100)}%`}</strong><span>50–75% required</span></article></div>{calibration.blockers.length ? <ul className="compactList">{calibration.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul> : <p className="decisionCopy">Empirical checks passed. Authority still requires the manual master switch.</p>}</section> : null}
    <section className={`panel full ${championshipBacktest.qualification_status === "qualified" ? "" : "managerBlockers"}`}><div className="panelHeader"><div><p className="eyebrow">Historical replay</p><h2>Championship model calibration</h2></div><StatusPill status={championshipBacktest.qualification_status}/></div><div className="metricGrid"><article className="metric"><small>Weekly probability samples</small><strong>{championshipBacktest.season_probability_calibration?.weekly_win_probability?.samples ?? 0}</strong><span>Brier: {championshipBacktest.season_probability_calibration?.weekly_win_probability?.brier_score ?? "awaiting outcomes"}</span></article>{championshipCalibration.map(([component, evidence]) => <article className="metric" key={component}><small>{component.replaceAll("_", " ")}</small><strong>{evidence.qualification_status.replaceAll("_", " ")}</strong><span>{evidence.samples ?? 0} historical samples</span></article>)}</div>{championshipBacktest.qualification_blockers?.length ? <ul className="compactList">{championshipBacktest.qualification_blockers.map((blocker) => <li key={blocker}>{blocker.replaceAll("_", " ")}</li>)}</ul> : <p className="decisionCopy">All championship components have passed their empirical thresholds.</p>}</section>
    {championship ? <section className="panel full"><div className="panelHeader"><div><p className="eyebrow">Shadow season model</p><h2>Championship simulation</h2></div><StatusPill status={championship.status}/></div>{championship.our_team ? <><div className="metricGrid"><article className="metric"><small>Championship</small><strong>{Math.round(championship.our_team.championship_probability * 1000) / 10}%</strong><span>shadow estimate</span></article><article className="metric"><small>Playoffs</small><strong>{Math.round(championship.our_team.playoff_probability * 1000) / 10}%</strong><span>all remaining weeks</span></article><article className="metric"><small>First-round bye</small><strong>{Math.round(championship.our_team.first_round_bye_probability * 1000) / 10}%</strong><span>seed distribution</span></article><article className="metric"><small>Simulation precision</small><strong>{championship.simulation_count?.toLocaleString() ?? "—"}</strong><span>±{Math.round(championship.our_team.championship_standard_error * 10000) / 100}% standard error</span></article><article className="metric"><small>Direct projections</small><strong>{Math.round((championship.projection_coverage ?? 0) * 100)}%</strong><span>90% promotion floor</span></article><article className="metric"><small>Legal team-weeks</small><strong>{Math.round((championship.structural_coverage ?? 0) * 100)}%</strong><span>after modeled streaming</span></article><article className="metric"><small>Replacement reliance</small><strong>{Math.round((championship.modeled_replacement_share ?? 0) * 1000) / 10}%</strong><span>10% promotion ceiling</span></article><article className="metric"><small>Live points fixed</small><strong>{Math.round((championshipLive?.fixed_points ?? 0) * 10) / 10}</strong><span>{Math.round((championshipLive?.remaining_mean ?? 0) * 10) / 10} expected remaining · {Object.entries(championshipLive?.player_states ?? {}).map(([state, count]) => `${count} ${state}`).join(" · ") || "awaiting games"}</span></article></div>{championshipFeatures.length ? <><h3 className="minorHeading">Decision features</h3><ul className="compactList">{championshipFeatures.map(([feature, evidence]) => <li key={feature}>{championshipFeatureLabels[feature] ?? feature}: {evidence.implemented ? "modeled" : "missing"} · {evidence.qualification_status.replaceAll("_", " ")}</li>)}</ul></> : null}</> : <div className="emptyState compact"><strong>Simulation blocked honestly</strong><span>{championship.blockers?.[0] ?? "Complete league projection coverage is required."}</span></div>}</section> : null}
    {moveCounterfactuals.length ? <section className="panel full"><div className="panelHeader"><div><p className="eyebrow">Do-nothing comparison</p><h2>Roster moves by title equity</h2></div><StatusPill status="analysis_only"/></div><div className="waiverList">{moveCounterfactuals.map((move, index) => <article key={`${move.add_player_id}-${move.drop_player_id}`}><span className="priority">{index + 1}</span><div><strong>Add {move.add_player_name} · Drop {move.drop_player_name}</strong><small>{move.acquisition_type ?? "unknown acquisition"} · championship {move.championship_probability_delta >= 0 ? "+" : ""}{Math.round(move.championship_probability_delta * 10000) / 100}% · playoffs {move.playoff_probability_delta >= 0 ? "+" : ""}{Math.round(move.playoff_probability_delta * 10000) / 100}%</small><p>{move.strategically_equivalent ? `Within simulation noise (±${Math.round(move.approximate_95_percent_margin * 10000) / 100}%).` : "Materially different from holding the roster in this simulation."}</p></div></article>)}</div><p className="methodNote">Screening only—these scenarios never submit a transaction.</p></section> : null}
    {decision?.urgent_alerts.length ? <section className="onClockBanner"><strong>Immediate attention</strong>{decision.urgent_alerts.map((alert) => <small key={alert}>{alert}</small>)}</section> : null}
    {recentNotices.length ? <section className="panel full"><div className="panelHeader"><div><p className="eyebrow">Durable local alerts</p><h2>Operations notifications</h2></div><StatusPill status={recentNotices.some((item) => item.severity === "warning") ? "attention" : "ready"}/></div><div className="waiverList">{recentNotices.map((notice) => <article key={notice.id}><div><strong>{notice.subject}</strong><small>{new Date(notice.created_at).toLocaleString()} · {notice.channel}</small><p>{notice.body}</p></div></article>)}</div></section> : null}
    <section className="panel full"><div className="panelHeader"><div><p className="eyebrow">Post-submit reconciliation</p><h2>Acquisition lifecycle</h2></div><StatusPill status={acquisitionLifecycle.status}/></div><div className="metricGrid"><article className="metric"><small>Active</small><strong>{acquisitionLifecycle.active_count}</strong><span>scheduled, pending, or reconciling</span></article><article className="metric"><small>Completed</small><strong>{acquisitionLifecycle.completed_count}</strong><span>publicly reconciled</span></article><article className="metric"><small>Failed</small><strong>{acquisitionLifecycle.failed_count}</strong><span>forces immediate re-plan</span></article></div>{acquisitionLifecycle.claims.length ? <div className="waiverList">{acquisitionLifecycle.claims.slice(0, 8).map((claim) => <article key={claim.command_id}><span className="priority">{claim.claim_priority ?? "—"}</span><div><strong>{claim.add_player_name}{claim.drop_player_name ? ` · Drop ${claim.drop_player_name}` : ""}</strong><small>{claim.outcome_status.replaceAll("_", " ")}{claim.transaction_id ? ` · ${claim.transaction_id}` : ""}</small>{claim.transaction_notes ? <p>{claim.transaction_notes}</p> : null}</div></article>)}</div> : <p className="decisionCopy">No submitted acquisition requires reconciliation.</p>}</section>
    {decision ? <div className="contentGrid">
      <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">Starting assignment</p><h2>Recommended lineup</h2></div><StatusPill status={decision.lineup_status}/></div><div className="lineupGrid">{decision.lineup.map((slot) => { const player = playerById.get(slot.player_id); return <article key={slot.slot_index}><span>{slot.slot}</span><strong>{name(slot.player_id)}</strong><small>{detail(player)}</small><p>{slot.reason}</p></article>; })}</div></section>
      {lineupPreview.length ? <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Exact swap sequence</p><h2>Execution preview</h2></div><StatusPill status={lineupExecution?.state ?? "analysis_only"}/></div><div className="waiverList">{lineupPreview.map((swap) => { const queued = lineupExecution?.queued.find((item) => item.sequence === swap.sequence); return <article key={swap.sequence}><span className="priority">{swap.sequence}</span><div><strong>{swap.parameters.to_player_name} → {swap.parameters.from_slot}</strong><small>{swap.parameters.from_player_name} → {swap.parameters.to_slot} · {queued ? `${queued.status}, eligible ${new Date(queued.not_before).toLocaleString()}` : lineupExecution?.reason ?? "not queued"}</small><p>{swap.reason}</p>{queued ? <a className="actionLink" href={`/actions#action-${queued.action_id}`}>View countdown or cancel</a> : null}</div></article>; })}</div></section> : null}
      <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Roster thesis</p><h2>Title outlook</h2></div></div><p className="decisionCopy">{decision.team_assessment.championship_outlook}</p><h3 className="minorHeading">This week</h3><p className="decisionCopy">{decision.team_assessment.weekly_strategy}</p><h3 className="minorHeading">Strengths</h3><ul className="compactList">{decision.team_assessment.strengths.map((item) => <li key={item}>{item}</li>)}</ul><h3 className="minorHeading">Vulnerabilities</h3><ul className="compactList">{decision.team_assessment.vulnerabilities.map((item) => <li key={item}>{item}</li>)}</ul></section>
      <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Championship horizon</p><h2>Waiver roster thesis</h2></div></div>{waiverHorizon ? <><p className="decisionCopy">{waiverHorizon.roster_thesis}</p><h3 className="minorHeading">Rest of season</h3><ul className="compactList">{waiverHorizon.rest_of_season_priorities.map((item) => <li key={item}>{item}</li>)}</ul><h3 className="minorHeading">Fantasy playoffs</h3><ul className="compactList">{waiverHorizon.playoff_priorities.map((item) => <li key={item}>{item}</li>)}</ul><h3 className="minorHeading">Churn rule</h3><p className="decisionCopy">{waiverHorizon.churn_policy}</p></> : <p className="decisionCopy">Waiting for a season-long roster thesis.</p>}</section>
      {irPlan ? <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">Roster capacity</p><h2>Injured reserve</h2></div><StatusPill status={plan.ir_execution?.state ?? irPlan.status}/></div><p className="decisionCopy">{irPlan.reason ?? `${irPlan.reserve_occupied}/${irPlan.reserve_capacity} reserve slots occupied.`}</p>{irPlan.actions.length ? <div className="waiverList">{irPlan.actions.map((action, index) => <article key={`${action.action_type}-${action.parameters.player_id}`}><span className="priority">{index + 1}</span><div><strong>{action.action_type === "MOVE_TO_IR" ? "Move" : "Remove"} {action.parameters.player_name}</strong><small>{action.parameters.observed_status} · exact reserve transition</small><p>{action.reason}</p></div></article>)}</div> : null}{irPlan.blocked.length ? <ul className="compactList">{irPlan.blocked.map((row) => <li key={`${row.action_type}-${row.player_id}`}>{row.player_name}: {row.reason}</li>)}</ul> : null}{!irPlan.actions.length && !irPlan.blocked.length && irPlan.status !== "not_applicable" ? <p className="decisionCopy">No IR action is needed.</p> : null}</section> : null}
      {pendingWaivers.length ? <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">Sleeper transaction state</p><h2>Pending waiver claims</h2></div><StatusPill status="pending"/></div><div className="waiverList">{pendingWaivers.map((claim, index) => <article key={claim.transaction_id}><span className="priority">{claim.sequence ?? index + 1}</span><div><strong>Add {claim.add_player_names.join(", ")}{claim.drop_player_names.length ? ` · Drop ${claim.drop_player_names.join(", ")}` : ""}</strong><small>Transaction {claim.transaction_id}</small></div></article>)}</div></section> : null}
      <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">Conditional claim tree</p><h2>Waiver strategy</h2></div><StatusPill status={decision.waiver_status}/></div><p className="decisionCopy">{decision.waiver_strategy}</p>{decision.waiver_claims.length ? <div className="waiverList">{decision.waiver_claims.map((claim) => <article key={`${claim.priority}-${claim.add_player_id}`}><span className="priority">{claim.priority}</span><div><strong>Add {name(claim.add_player_id)}{claim.drop_player_id ? ` · Drop ${name(claim.drop_player_id)}` : ""}</strong><small>{claim.claim_type} · {claim.horizon.replaceAll("_", " ")} · role: {claim.expected_roster_role} · re-evaluate Week {claim.reevaluate_after_week}</small><p><b>Now:</b> {claim.immediate_case}<br/><b>Season:</b> {claim.season_case}<br/><b>Drop cost:</b> {claim.drop_cost}<br/><b>Exit:</b> {claim.exit_plan}<br/>{claim.contingency} · {claim.reason}</p></div></article>)}</div> : <div className="emptyState compact"><strong>No claim proposed</strong><span>The expert compared the roster with doing nothing.</span></div>}</section>
      <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">High-upside, low-volume automation</p><h2>Trade market</h2></div><StatusPill status={tradeExecution?.state ?? decision.trade_status ?? "waiting"}/></div><p className="decisionCopy">{decision.trade_strategy ?? "Waiting for the next whole-league manager analysis."}</p>{tradeTargets.length ? <div className="waiverList">{tradeTargets.map((target, index) => <article key={`${target.target_roster_id}-${target.target_player_ids.join("-")}`}><span className="priority">{index + 1}</span><div><strong>{target.recommended_action === "propose" ? "Propose for" : "Watch"} {target.target_player_ids.map(name).join(" + ")} from roster {target.target_roster_id}</strong><small>Offer {target.offer_player_ids.map(name).join(" + ")} · {target.upside_tier} upside · {Math.round(target.confidence * 100)}% · {target.evidence_status} · ceiling: {target.cost_ceiling}</small><p><b>Title case:</b> {target.championship_case}<br/><b>Their case:</b> {target.counterparty_case}<br/><b>Trigger:</b> {target.timing_trigger}<br/><b>Risk:</b> {target.risk}<br/>{target.reason}</p></div></article>)}</div> : <div className="emptyState compact"><strong>No trade worth pursuing</strong><span>The system holds unless a confirmed, high-upside trade clears every gate.</span></div>}{incomingTradeDecisions.length ? <><h3 className="minorHeading">Incoming offer decisions</h3><div className="waiverList">{incomingTradeDecisions.map((item) => <article key={item.offer_fingerprint}><div><strong>{item.action.toUpperCase()} · {item.upside_tier} upside</strong><small>{Math.round(item.confidence * 100)}% · {item.evidence_status}</small><p>{item.championship_case}<br/>{item.reason}</p></div></article>)}</div></> : null}{tradePreview.length ? <><h3 className="minorHeading">Exact execution preview</h3><div className="waiverList">{tradePreview.map((item) => { const queued = tradeExecution?.queued.find((entry) => entry.action_type === item.action_type); return <article key={`${item.action_type}-${item.parameters.counterparty_roster_id}-${item.parameters.offer_fingerprint ?? "proposal"}`}><div><strong>{item.action_type.replaceAll("_", " ")} with {item.parameters.counterparty_account_label}</strong><small>Send {item.parameters.send_assets.map((asset) => asset.player_name).join(" + ") || "nothing"} · Receive {item.parameters.receive_assets.map((asset) => asset.player_name).join(" + ") || "nothing"} · {queued ? queued.status : tradeExecution?.reason ?? "not queued"}</small><p>{item.reason}</p>{queued ? <a className="actionLink" href={`/actions#action-${queued.action_id}`}>View exact action or cancel</a> : null}</div></article>; })}</div></> : null}<p className="methodNote">Outbound limit: one proposal per week, seven-day counterparty cooldown, 24-hour expiry. Every click is exact-match and verified afterward.</p></section>
      {waiverPreview.length ? <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">Exact transaction instructions</p><h2>Acquisition preview</h2></div><StatusPill status={acquisitionExecution?.state ?? "analysis_only"}/></div><div className="waiverList">{waiverPreview.map((item) => { const queued = acquisitionExecution?.queued.find((entry) => entry.sequence === item.sequence); const deferred = acquisitionExecution?.deferred?.find((entry) => entry.sequence === item.sequence); return <article key={`${item.sequence}-${item.parameters.add_player_id}`}><span className="priority">{item.parameters.claim_priority}</span><div><strong>{item.action_type === "WAIVER_CLAIM" ? "Claim" : "Add"} {item.parameters.add_player_name}{item.parameters.drop_player_name ? ` · Drop ${item.parameters.drop_player_name}` : ""}</strong><small>{item.parameters.horizon.replaceAll("_", " ")} · Sleeper observed: {item.parameters.observed_acquisition_type} · {queued ? queued.status : deferred?.reason ?? acquisitionExecution?.reason ?? "not queued"}</small><p>{item.parameters.contingency} · Exit: {item.parameters.exit_plan} · {item.reason}</p>{queued ? <a className="actionLink" href={`/actions#action-${queued.action_id}`}>View countdown or cancel</a> : null}</div></article>; })}</div>{acquisitionExecution?.continuation_policy === "verify_reconcile_replan" ? <p className="methodNote">Only the first move is eligible. Later moves require verified completion, a refreshed roster, and a new expert decision.</p> : null}</section> : null}
      <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Evidence control</p><h2>Known gaps</h2></div></div>{decision.evidence_gaps.length ? <ul className="compactList">{decision.evidence_gaps.map((gap) => <li key={gap}>{gap}</li>)}</ul> : <p className="decisionCopy">No material evidence gaps reported.</p>}<p className="methodNote">Provider: {plan.expert?.provider ?? "—"} · {plan.expert?.model ?? "—"}<br/>Weather: {plan.data_quality?.weather_status ?? "unavailable"} · {plan.data_quality?.weather_coverage?.forecast_count ?? 0}/{plan.data_quality?.weather_coverage?.eligible_game_count ?? 0} exposed games<br/>Web research: {plan.expert?.used_web_search ? "used" : "not used"} · Execution: {plan.execution_state}</p></section>
      {researchEvidence.length ? <section className="panel spanTwo"><div className="panelHeader"><div><p className="eyebrow">Current research</p><h2>Evidence used in the decision</h2></div></div><div className="waiverList">{researchEvidence.map((evidence, index) => <article key={`${evidence.source_url}-${index}`}><span className="priority">{index + 1}</span><div><strong>{evidence.player_id ? name(evidence.player_id) : "League context"} · {evidence.source_name}</strong><small>{evidence.published_at}</small><p>{evidence.finding}<br/><b>Decision impact:</b> {evidence.decision_impact}</p><a className="actionLink" href={evidence.source_url} target="_blank" rel="noreferrer">Open source</a></div></article>)}</div></section> : null}
    </div> : <section className="panel full"><div className="emptyState"><strong>Expert analysis unavailable</strong><span>{plan.error ?? plan.blockers[0] ?? "Waiting for the first grounded analysis."}</span></div></section>}
    {plan.blockers.length ? <section className="panel full managerBlockers"><div className="panelHeader"><div><p className="eyebrow">Safety boundary</p><h2>Execution blockers</h2></div></div><ul className="compactList">{plan.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></section> : null}
  </>;
}
